# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECv2QMxXuMW1vZb-RDdtWu_na3uQxRrE

## Data Science Tools and Ecosystem

## In this notebook, Data Science Tools and Ecosystem are Summarized

**Objectives:**
+ Some of the popular langauges that Data Scientists use are
+ Some of the commonly used libraries used by Data Scientists include
* Data Science Tools

## Some of the popular languages that Data Scientists use are:

1. python
2. Java
3. R

## Data Science Tools

| Data Science Tools|
|-------------------|
|1. Jupyter note book|
|2. R studio|
|3. Visual Studio Code|

## Some of the commonly used libraries used by Data Scientists include:

1. Pandas(Scientific Computing)
2. MathPlotLib(Data Vizualization)
3. SciKit-Learn(Machine_learning)

### Below are a few examples of evaluating arithmetic expressions in python
"""

# This is a simple arithmetic expression to multiply then add integers
(3*4)+5

#This will convert 200 minutes to hours by dividing by 60
200/60

"""## Author
Qasim Arigbabu
"""